### ISSUE TITLE
Invalid CHIP ID: 0x60

### ISSUE THREAD

**Issue by djcaff263** [pimoroni/bme680#12]
When running example programs is get 
`
Traceback (most recent call last):
  File "read-all.py", line 6, in <module>
    sensor = bme680.BME680()
  File "build/bdist.linux-armv7l/egg/bme680/__init__.py", line 27, in __init__
RuntimeError: BME680 Not Found. Invalid CHIP ID: 0x60
`
I can't find `build/bdist.linux-armv7l/egg/bme680`. I'm using the adafruit bme680 board and the chip id is 0xD0. I just dont know where to change this.

**Comment by JavanXD** [comment]
What was the problem? Running into the same issue.

**Comment by djcaff263** [comment]
Make sure you are actually working with a bee 680 and not a different chip. I had this problem because they sent me the wrong chip so I thought I was working with a 680 but it was actually a 280.  Just double check your chip and make sure.

**Comment by martinharnevie** [comment]
ChipIDs
BME680   0x61
BME280   0x60
BMP280   0x58
BMP388   0x50
